### ISSUE TITLE
sql tags (sometimes) not hashing when running rollup in watch mode

### ISSUE THREAD

**Issue by victorouse** [porsager/HashQL#2]
Hey @porsager, real big fan of this project!

I'm having a really weird issue with my setup. I'm running rollup in watch mode, and every now and then my queries in the `sql` tags do not hash in my bundle. 

Here's a gif of the weirdness:

![weirdness](https://user-images.githubusercontent.com/1930296/67631738-51cff980-f8ee-11e9-8dbf-25931bfed7ad.gif)

My `rollup.config.js`:

```
import fs from 'fs'
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import copy from 'rollup-plugin-copy'
import HashQL from 'hashql/rollup'

export default {
  input: 'client/src/index.js',
  output: {
    file: 'client/dist/bundle.js',
    format: 'iife',
    sourcemap: true,
  },
  plugins: [
    resolve(),
    commonjs(),
    HashQL({
      tags: ['sql', 'node'],
      output: queries =>
        fs.writeFileSync(
          'server/queries.json',
          JSON.stringify(queries, null, 2),
        ),
    }),
    copy({
      targets: [
        {
          src: 'client/src/index.html',
          dest: 'client/dist',
        },
      ],
    }),
  ],
}
```

And the `scripts` section of my `package.json`:

```
  "scripts": {
    "client:build": "rollup -c client/rollup.config.js",
    "client:watch": "rollup -c client/rollup.config.js -w",
    "client:dev": "npm-run-all --parallel client:start client:watch",
    "client:start": "serve -s client/dist",
    "server:start": "node server",
    "server:watch": "nodemon --watch ./client --watch ./server ./server",
    "start": "npm-run-all --parallel server:start client:start",
    "dev": "npm-run-all --parallel server:watch client:dev"
  }
```

And `dependencies` and `devDependencies` if it helps: 

```
  "dependencies": {
    "body-parser": "^1.19.0",
    "bss": "^1.6.3",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "hashql": "0.0.8",
    "mergerino": "^0.4.0",
    "mithril": "^2.0.4",
    "pg-promise": "^9.3.3",
    "stags": "^1.0.0-rc27"
  },
  "devDependencies": {
    "meiosis-tracer": "^3.0.0",
    "nodemon": "^1.19.4",
    "npm-run-all": "^4.1.5",
    "rollup": "^1.25.2",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-copy": "^3.1.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "serve": "^11.2.0"
  }
```

It seems to *only* happen in watch mode, since if I kill it and start it again, it hashes as expected.

Any ideas?

**Comment by victorouse** [comment]
Not a fix, but hopefully a hint - if I remove the `matchRegex` from:

https://github.com/porsager/hashql/blob/master/rollup.js#L14

Then the issue goes away. Perhaps it has something to do with the return value from `transform`?

https://github.com/rollup/rollup/blob/master/docs/05-plugin-development.md#transform

**Comment by JAForbes** [comment]
Hey what happens if you use fs.promises.writeFile?

**Comment by victorouse** [comment]
> Hey what happens if you use fs.promises.writeFile?

Same thing :(

**Comment by porsager** [comment]
Hey @victorouse 

Awesome!! Cool you're managing without any docs 😃

I'll take a closer look, it might very well have to do with caching in watch mode.

**Comment by porsager** [comment]
Haha.. Wonderful javascript strikes again 😃 I got burned by thinking test would be faster than match, but then `test` has this neat little gotcha.

> RexExp.prototype.test: It is worth noting that the lastIndex will not reset when testing a different string.

```
const r = /foo/g
// regex.lastIndex is at 0
regex.test('foo'); // true

// regex.lastIndex is now at 3
regex.test('foo'); // false

// regex.lastIndex is at 0
regex.test('barfoo') // true

// regex.lastIndex is at 6
regex.test('foobar') //false
```

I've changed to using `match` which fixes the issue. I was not aware `test` had the same behavior as `exec`.

**Comment by porsager** [comment]
Apparently this is only when `global` is set, so I guess I could have removed `global` and kept `test` instead of replacing it with `match`.

Further investigation shows that pre Firefox 27, `match` with global actually worked the same as `test`
> Starting with Firefox 27, this method has been adjusted to conform with the ECMAScript specification. When match() is called with a global regular expression, the RegExp.lastIndex property (if specified) will be reset to 0 (bug 501739).

It's somehow neat that Javascript is still able to surprise me. I guess you could say it's a sign of a healthy relationship 😂

**Comment by JAForbes** [comment]
@porsager this has bit me before and my reaction to JS was a lot less amicable than yours 😂

**Comment by porsager** [comment]
Haha, well we're already knees deep in, so what's another weird gotcha 😝 

The interesting thing about this bug is that it would have hit at other weird times too, not only because of using `watch` mode, but also if another file contained hql and the lastIndex was later.. I guess this shows it still hasn't been through the real tests yet...

The good thing about this bug is that I got around to add source map support while I was at it ;)

**Comment by JAForbes** [comment]
> The good thing about this bug is that I got around to add source map support while I was at it ;)

👏 You are indeed a sorcerer 🧙‍♂️

**Comment by JAForbes** [comment]
Apparently it's perl's fault 💣

> I based JS regexp on then-contemporary Perl 4 regex. Hey, it was the 90s!

[Brendan Eich - Twitter](http://twitter.com/BrendanEich/status/231066800304046080)

**Comment by victorouse** [comment]
Haha, you guys are the greatest.

Thanks for the speedy fix @porsager, works like a charm!

Happy hashing. ;-)
